import{a as h,S as B,i as n}from"./assets/vendor-BSTwZ_tR.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const q="52329840-3cdbe1d1ca17a86ceb553d9b5";h.defaults.baseURL="https://pixabay.com/api/";h.defaults.params={};h.defaults.params.key=q;async function d(s,e=1){return(await h.get("",{params:{q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:e}})).data}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),g=document.querySelector(".search-more-btn"),C=new B(".gallery-item a",{captionsData:"alt",captionDelay:250});function y(s){const e=s.map(({tags:i,likes:c=0,views:t=0,comments:r=0,downloads:l=0,webformatURL:v,largeImageURL:S})=>`
        <li class="gallery-item">
          <a class="gallery-origin-img" href="${S}">
            <img class="gallery-prewiew-img" src="${v}" alt="${i}" width="360" height="152"/>
            </a>
            <div class="gallery-info-wrapper">
              <h4 class="gallery-info-item">Likes<span>${c}<span></h4>
              <h4 class="gallery-info-item">Views<span>${t}<span></h4>
              <h4 class="gallery-info-item">Comments<span>${r}<span></h4>
              <h4 class="gallery-info-item">Downloads<span>${l}<span></h4>
            </div>
        </li>
        `).join("");p.insertAdjacentHTML("beforeend",e),C.refresh()}function u(){p.innerHTML=""}function w(){m.classList.remove("hide")}function L(){m.classList.contains("hide")||m.classList.add("hide")}function b(){g.classList.remove("hide")}function o(){g.classList.contains("hide")||g.classList.add("hide")}let a=1,f="";const P=document.querySelector(".form");P.addEventListener("submit",R);async function R(s){if(s.preventDefault(),u(),o(),a=1,f=String(s.target.elements["search-text"].value.toLowerCase().trim()),!f)return o(),n.error({icon:"",position:"topRight",message:"Please, enter your search query!",timeout:5e3,progressBar:!1,close:!1,messageColor:"white"});w();try{const e=await d(f,a);if(!e.hits.length)return u(),o(),n.info({icon:"",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",timeout:5e3,progressBar:!1,close:!1,messageColor:"white"});if(y(e.hits),e.hits.length*a>e.totalHits)return o(),n.info({message:"We're sorry, but you've reached the end of search results.",icon:"",position:"topRight",timeout:5e3,progressBar:!1,close:!1,messageColor:"white"});b(),s.target.reset()}catch(e){return a=1,console.error(e.message),u(),o(),n.error({icon:"",position:"topRight",message:"Something went wrong. Please try again later.",timeout:5e3,progressBar:!1,close:!1,messageColor:"white"})}finally{L()}}g.addEventListener("click",M);async function M(s){o(),a+=1,w();try{const e=await d(f,a);y(e.hits);const i=document.querySelector(".gallery-item");if(i&&window.scrollBy({top:2*i.getBoundingClientRect().height,behavior:"smooth"}),e.hits.length*a>e.totalHits)return o(),n.info({message:"We're sorry, but you've reached the end of search results.",icon:"",position:"topRight",timeout:5e3,progressBar:!1,close:!1,messageColor:"white"});b()}catch(e){return a=1,console.error(e.message),u(),o(),n.error({icon:"",position:"topRight",message:"Something went wrong. Please try again later.",timeout:5e3,progressBar:!1,close:!1,messageColor:"white"})}finally{L()}}
//# sourceMappingURL=index.js.map
