import{a as m,S as q,i as c}from"./assets/vendor-BSTwZ_tR.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const P="52329840-3cdbe1d1ca17a86ceb553d9b5";m.defaults.baseURL="https://pixabay.com/api/";m.defaults.params={};m.defaults.params.key=P;async function h(o,e=1){const s=await m.get("",{params:{q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:e}});return console.log(s.data),console.log(e),s.data}const p=document.querySelector(".gallery"),g=document.querySelector(".loader"),f=document.querySelector(".search-more-btn"),C=new q(".gallery-item a",{captionsData:"alt",captionDelay:250});function y(o){const e=o.map(({tags:s,likes:n=0,views:t=0,comments:r=0,downloads:l=0,webformatURL:v,largeImageURL:B})=>`
        <li class="gallery-item">
          <a class="gallery-origin-img" href="${B}">
            <img class="gallery-prewiew-img" src="${v}" alt="${s}" width="360" height="152"/>
            </a>
            <div class="gallery-info-wrapper">
              <h4 class="gallery-info-item">Likes<span>${n}<span></h4>
              <h4 class="gallery-info-item">Views<span>${t}<span></h4>
              <h4 class="gallery-info-item">Comments<span>${r}<span></h4>
              <h4 class="gallery-info-item">Downloads<span>${l}<span></h4>
            </div>
        </li>
        `).join("");p.insertAdjacentHTML("beforeend",e),C.refresh()}function u(){p.innerHTML=""}function L(){g.classList.remove("hide")}function w(){g.classList.contains("hide")||g.classList.add("hide")}function b(){f.classList.remove("hide")}function i(){f.classList.contains("hide")||f.classList.add("hide")}function S(o,e,s){if(e*s>=o.totalHits)return i(),c.info({message:"We're sorry, but you've reached the end of search results.",icon:"",position:"topRight",timeout:5e3,progressBar:!1,close:!1,messageColor:"white"}),!0}let a=1,d="";const R=document.querySelector(".form");R.addEventListener("submit",M);async function M(o){if(o.preventDefault(),u(),i(),a=1,d=String(o.target.elements["search-text"].value.toLowerCase().trim()),!d)return c.error({icon:"",position:"topRight",message:"Please, enter your search query!",timeout:5e3,progressBar:!1,close:!1,messageColor:"white"});L();try{const e=await h(d,a);if(!e.hits.length)return u(),i(),c.info({icon:"",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",timeout:5e3,progressBar:!1,close:!1,messageColor:"white"});y(e.hits),S(e,a,15)||b(),o.target.reset()}catch(e){return a=1,console.error(e.message),u(),i(),c.error({icon:"",position:"topRight",message:"Something went wrong. Please try again later.",timeout:5e3,progressBar:!1,close:!1,messageColor:"white"})}finally{w()}}f.addEventListener("click",$);async function $(o){i(),a+=1,L();try{const e=await h(d,a);y(e.hits);const s=document.querySelector(".gallery-item");s&&window.scrollBy({top:2*s.getBoundingClientRect().height,behavior:"smooth"}),S(e,a,15)||b()}catch(e){return a=1,console.error(e.message),u(),i(),c.error({icon:"",position:"topRight",message:"Something went wrong. Please try again later.",timeout:5e3,progressBar:!1,close:!1,messageColor:"white"})}finally{w()}}
//# sourceMappingURL=index.js.map
